### PR TITLE
Introduce Vorlon

### PR DESCRIPTION
**Pull request by michaelpelletier**
Idea for this PR covers a few different things.

- [x] Use images with transparency and a CSS overlay so that we don't need different background images for each team.
- [x] Introduce an animated "being hacked" background for when the aliens are jamming.
- [x] Introduce the Vorlon font. 
  - [x] Vorlon font should only affect certain things.
- [ ] Clean up the images a bit more.

Animated Example

vorlon2

### CODE REVIEW

**Comment by FifthSurprise** [comment]
Everything looks fine to me.  Unless you want to tidy up images more, I'll merge.

**Comment by michaelpelletier** [comment]
@FifthSurprise Yeah, I want to tweak them some, since the grid and "flight path" lines get kind of gross during the "static" periods. I also want to make it look kind of more... corrupted.

**Comment by FifthSurprise** [comment]
@michaelpelletier Still in progress about the images?

I'd prefer to merge in and then do another PR for improved images whenever you get to it.

**Comment by michaelpelletier** [comment]
I guess it's fine for a first pass, mostly since I don't know when I'll have time to do more with it.

**Comment by FifthSurprise** [comment]
Merging and will set up another issue to fix the images later.

**Pull request merged**
