### PR TITLE
Newspaper

### PR DESCRIPTION
**Pull request by michaelpelletier**
Will close https://github.com/MegaGameSociety/WatchTheSkiesDashboard/issues/26 when it is finished.

### Newspaper Page
screen shot 2015-12-05 at 10 48 31 pm

### Print Preview
screen shot 2015-12-05 at 10 48 27 pm

### CODE REVIEW

**Comment by michaelpelletier** [comment]
WIP. 

Will need to do some testing while I'm in the office / with a printer to be able to play with some of the font-sizing things. Also will need to generate some more accurate articles. 

I also began playing with injecting HTML directly into the article to create some more complex articles.

screen shot 2015-12-05 at 11 19 23 pm

**Comment by FifthSurprise** [comment]
@michaelpelletier Best way to test this would just be to save this as pdf and see how it looks landscape wise.  That's good enough for our purposes.

**Comment by michaelpelletier** [comment]
m'kay, thanks @FifthSurprise. Also, what are your feelings on the additions of Title / Author / Quote sections for the article content itself. My suspicion is that it may be going overboard.

**Comment by FifthSurprise** [comment]
I thought about it a bit and I think with the twitter integration, this doesn't make as much sense.  The author would be whoever is the news player so using the DEN or GNN banner to identify them is fine.  Consequently, quotations won't be identifiable when twitter integration is back up.  However, using the lines to separate a news article probably would look good.

Assuming each article is 140 characters and we allow like two or three images on the paper, it should be able to fit one page.  But vertical space is a premium so having the big Newspaper header, banner images, and Round # taking up almost half the page (that's what it seems from the image) is not good.

**Comment by michaelpelletier** [comment]
Sounds good, I'll make some more adjustments tomorrow!

**Comment by FifthSurprise** [comment]
One more thing I just thought of, probably should just make the bg-color of the newspaper white so as to not to mess with printer toner.

**Comment by michaelpelletier** [comment]
:+1:

**Comment by michaelpelletier** [comment]
@FifthSurprise Barring any other changes, this might be ready to go! I can tighten it up more if you think each one might have their own images, and let me know what kinds of things those might be?

screen shot 2015-12-10 at 6 57 31 pm

Here is the actual generated PDF.
[WatchTheSkiesDashboard.pdf](https://github.com/MegaGameSociety/WatchTheSkiesDashboard/files/58895/WatchTheSkiesDashboard.pdf)

**Pull request merged**
